export const ADD_AGENT = 'ADD_AGENT'
export const SHOW_AGENT_CONFIG_FORM = 'SHOW_AGENT_CONFIG_FORM'
export const HIDE_AGENT_CONFIG_FORM = 'HIDE_AGENT_CONFIG_FORM'

export const CREATE_WORKER_CONFIG = 'CREATE_WORKER_CONFIG'

export const REMOVE_AGENT = 'REMOVE_AGENT'

export const ADD_AGENT_RESPONSE = 'ADD_AGENT_RESPONSE'
export const UPDATE_AGENT_STATE = 'UPDATE_AGENT_STATE'

export const SHOW_PYODIDE_COMMAND_BOX = 'SHOW_PYODIDE_COMMAND_BOX'
export const HIDE_PYODIDE_COMMAND_BOX = 'HIDE_PYODIDE_COMMAND_BOX'
