export const ADD_AGENT = 'ADD_AGENT'
export const REMOVE_AGENT = 'REMOVE_AGENT'

export const WAIT_FOR_AGENT_RESPONSE = 'WAIT_FOR_AGENT_RESPONSE'
export const RECEIVED_AGENT_RESPONSE = 'RECEIVED_AGENT_RESPONSE'
export const ADD_AGENT_RESPONSE = 'ADD_AGENT_RESPONSE'

export const SHOW_PYODIDE_COMMAND_BOX = 'SHOW_PYODIDE_COMMAND_BOX'
export const HIDE_PYODIDE_COMMAND_BOX = 'HIDE_PYODIDE_COMMAND_BOX'
